/* Autogenerated with kurento-module-creator */

#ifndef __NUBO_TRACKER_IMPL_HPP__
#define __NUBO_TRACKER_IMPL_HPP__

#include "FilterImpl.hpp"
#include "NuboTracker.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace nubotracker
{
class NuboTrackerImpl;
} /* nubotracker */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::nubotracker::NuboTrackerImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace nubotracker
{

class NuboTrackerImpl : public FilterImpl, public virtual NuboTracker
{

public:

  NuboTrackerImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~NuboTrackerImpl () {};

  void setThreshold(int threshold);
  void setMinArea(int minArea);
  void setMaxArea(float maxArea);
  void setDistance(int distance);
  void setVisualMode(int mode);

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  GstElement *nubo_tracker = NULL;
  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* nubotracker */
} /* module */
} /* kurento */

#endif /*  __NUBO_TRACKER_IMPL_HPP__ */
