
/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "MediaPipelineImpl.hpp"
#include <NuboNoseDetectorImplFactory.hpp>
#include "NuboNoseDetectorImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_nubo_nose_detector_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoNuboNoseDetectorImpl"

#define VIEW_NOSES "view-noses"
#define DETECT_BY_EVENT "detect-event"
#define SEND_META_DATA "send-meta-data"
#define FACTOR_SCALE "multi-scale-factor"
#define X_EVERY_4_FRAMES "process-x-every-4-frames"
#define WIDTH_TO_PROCESS "width-to-process"

namespace kurento
{
  namespace module
  {
    namespace nubonosedetector
    {

      NuboNoseDetectorImpl::NuboNoseDetectorImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline)  : FilterImpl (config, std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline)) 
      {
 
	g_object_set (element, "filter-factory", "nubonosedetector", NULL);
  
	g_object_get (G_OBJECT (element), "filter", &nubo_nose, NULL);

	if (NULL == nubo_nose) {
	  throw KurentoException (MEDIA_OBJECT_NOT_AVAILABLE,
				  "Media Object not available");
	}

	g_object_unref(nubo_nose); 
      }

      void NuboNoseDetectorImpl::showNoses (int viewNoses)
      {
	g_object_set(G_OBJECT (nubo_nose), VIEW_NOSES, viewNoses, NULL);
      }


      void NuboNoseDetectorImpl::detectByEvent(int event)
      {
  
	g_object_set(G_OBJECT (nubo_nose), DETECT_BY_EVENT, event, NULL);
  
      }
  
      void NuboNoseDetectorImpl::sendMetaData(int metaData)
      {
	g_object_set(G_OBJECT (nubo_nose),SEND_META_DATA , metaData, NULL);
      }

      void NuboNoseDetectorImpl::multiScaleFactor(int scaleFactor)
      {
	
	g_object_set(G_OBJECT (nubo_nose),FACTOR_SCALE , scaleFactor, NULL);
      }

      void NuboNoseDetectorImpl::processXevery4Frames(int xper4)
      {
	g_object_set(G_OBJECT (nubo_nose),X_EVERY_4_FRAMES , xper4, NULL);
      }

      void NuboNoseDetectorImpl::widthToProcess(int width)
      {
	g_object_set(G_OBJECT (nubo_nose),WIDTH_TO_PROCESS , width, NULL);
      }

      MediaObjectImpl *
      NuboNoseDetectorImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
      {
	return new NuboNoseDetectorImpl (config, mediaPipeline);
      }

      NuboNoseDetectorImpl::StaticConstructor NuboNoseDetectorImpl::staticConstructor;

      NuboNoseDetectorImpl::StaticConstructor::StaticConstructor()
      {
	GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
				 GST_DEFAULT_NAME);
      }

    } /* nubonosedetector */
  } /* module */
} /* kurento */
